//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppFactory.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailQueue
    {
        public int QueueID { get; set; }
        public long UserID { get; set; }
        public int ConfigID { get; set; }
        public System.DateTime SendDate { get; set; }
        public int TemplateID { get; set; }
        public bool Status { get; set; }
    
        public virtual EmailConfig EmailConfig { get; set; }
        public virtual EmailTemplate EmailTemplate { get; set; }
        public virtual User User { get; set; }
    }
}
