//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppFactory.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonalDetail
    {
        public long PersonalDetailID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public bool Gender { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string TelephoneNumber { get; set; }
        public string MobileNumber { get; set; }
        public int CountryID { get; set; }
        public string PostalCode { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual User User { get; set; }
    }
}
